export const MY_SKILLS = [
  {
    name: 'Java',
    icon: 'java',
    alt: 'Logo do Java',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Spring Boot',
    icon: 'springboot',
    alt: 'Logo do Spring Boot',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Django',
    icon: 'django',
    alt: 'Logo do Django',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Python',
    icon: 'python',
    alt: 'Logo do Python',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Typescript',
    icon: 'typescript',
    alt: 'Logo do Typescript',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Angular',
    icon: 'angular',
    alt: 'Logo do Angular',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Nodejs',
    icon: 'nodejs',
    alt: 'Logo do Nodejs',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Postgres',
    icon: 'postgres',
    alt: 'Logo do PostgreSQL',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'AWS Cloud',
    icon: 'aws',
    alt: 'Logo da AWS Cloud',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Azure',
    icon: 'azure',
    alt: 'Logo do Azure',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Docker',
    icon: 'docker',
    alt: 'Logo do Docker',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Portainer',
    icon: 'portainer',
    alt: 'Logo do Portainer',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Nginx',
    icon: 'nginx',
    alt: 'Logo do Nginx',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Sentry',
    icon: 'sentry',
    alt: 'Logo do Sentry',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Git',
    icon: 'git',
    alt: 'Logo do Git',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Figma',
    icon: 'figma',
    alt: 'Logo do Figma',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Bootstrap',
    icon: 'bootstrap',
    alt: 'Logo do Bootstrap',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Angular Material',
    icon: 'angular-material',
    alt: 'Logo do Angular Material',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Tailwind',
    icon: 'tailwind',
    alt: 'Logo do Tailwind',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'MySQL',
    icon: 'mysql',
    alt: 'Logo do MySQL',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'RxJs',
    icon: 'rxjs',
    alt: 'Logo do Rxjs',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Junit',
    icon: 'junit5',
    alt: 'Logo do Junit',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Scss',
    icon: 'scss',
    alt: 'Logo do SCSS',
    aosAnimation: 'zoom-out-up',
  },
];
