export const JOBS = [
    {
    company: 'IFAC',
    position: 'Software Developer',
    description: [
      'Desenvolvimento e integração de sistemas utilizando Python, Django, PostgreSQL, dentre outros;',
      'Conteinerização de serviços com Docker;',
      'Manutenção e evolução do sistema SUAP (Sistema Unificado de Administração Pública) no Instituto Federal do Acre;',
      "Controle de versionamento com Git, seguindo boas práticas de branching (main, staging, feature branches) e integração contínua com pipelines automatizados;",
      'Principais Tecnologias utilizadas: Python, Django, PostgreSQL, Docker, Wordpress, Elementor, Figma, Git dentre outras.',
    ],
    duration: 'Abril 2025 - Atualmente',
    icon: '../../../assets/icons/ifac-icon.svg',
  },
  {
    company: 'VINT Global',
    position: 'Desenvolvedor Full Stack',
    description: [
      'Desenvolvimento de APIs REST e integração com o Front-End;',
      'Desenvolvimento e integração de sistemas utilizando XML, XSLT e Web Services, em conformidade com as normas e padrões de Documentos Fiscais Eletrônicos;',
      'Conteinerização de serviços com Docker;',
      'Implementações com NGinx para redirecionamento de rotas e integrações com aplicações em Angular;',
      'Principais Tecnologias utilizadas: Java, Spring Boot e Angular 16+, Strapi, Xml, Xslt, Web Services, Docker, Junit5, Nginx, Strapi, Banco de Dados Oracle, Figma, dentre outras.',
    ],
    duration: 'Agosto 2024 - Abril 2025',
    icon: '../../../assets/icons/vintglobal-icon.svg',
  },
  {
    company: 'Freelancer',
    position: 'Desenvolvedor Full Stack',
    description: [
      'Desenvolvimento de projetos Freelancer e refinamento de portfólio;',
      'Projeto Autenticação JWT com Spring Boot, Angular, Azure/Kubernetes e Docker.',
      'Projeto Reset Password via e-mail desenvolvido em Angular, Java/Spring boot e AWS Cloud.',
      'Portfólio Dev desenvolvido em Angular e Material com SSR.',
    ],
    duration: 'Janeiro 2024 - Julho 2024',
    icon: '../../../assets/icons/freelancer-icon.svg',
  },
  {
    company: 'Contax S.A',
    position: 'Desenvolvedor Full Stack Jr.',
    description: [
      'Desenvolvimento, manutenção e migração de sistemas da CEF (Caixa Econômica Federal) por prazo determinado.',
      'Projetos entregues dentro do prazo e conforme os requisitos solicitados.',
      'Principais tecnologias utilizadas: Azure DevOps, Docker, Java, Junit 5, SQL Server, PHP e Git.',
      'Time 100% ágil: Scrum/Kanban e XP.',
    ],
    duration: 'Setembro 2023 - Novembro 2023',
    icon: '../../../assets/icons/contax-icon.svg',
  },
  {
    company: 'UFAC',
    position: 'Bolsista em curso de Desenvolvimento Web Full Stack',
    description: [
      'Desenvolvimento de sistemas para as empresas Motorola e Instituto Eldorado por meio do projeto WebAcademy.',
      'Desenvolvi o front-end dos sistemas demandados pelos parceiros do projeto.',
      'Atuei na correções de bugs/refatoração nas API’s e integrações com o Front-End.',
      'Principais tecnologias utilizadas: Java, Angular, Spring Boot, Typescript, Nodejs, CI/CD, Cypress, Jest, AWS Cloud, Junit5.',
      'Time 100% ágil: Scrum/Kanban e XP.',
    ],
    duration: 'Março 2022 - Outubro 2022',
    icon: '../../../assets/icons/ufac-icon.svg',
  },
];
